### PR TITLE
Include a stack template and instructions for using it

### PR DESCRIPTION
**Pull request by csasarak**
The URL in the readme is what the location of the template file would be if it were merged. If there's a more robust way to include links to files on github I'm up for doing that. For the time being it can be tested with: 

```sh
stack new --resolver=lts-13.0 --solver polysemy-base https://github.com/csasarak/polysemy/raw/stack-template/polysemy-template.hsfiles
```

lts is specified because otherwise stack will download and go through every lts plan looking for one that includes polysemy/polysemy-plugin before generating `extra-deps` and downloading from hackage. Aside from that being the lts that polysemy itself is using there was no other reason to prefer it. If polysemy is included in stack, we can remove the `--resolver` and `--solver` switches.

Mysteriously, `stack` sometimes ends with an error, which is why this is still a draft.

Addresses https://github.com/isovector/polysemy/issues/44

### CODE REVIEW

File: polysemy-template.hsfiles [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+homepage:            https://github.com/{{github-username}}{{^github-username}}githubuser{{/github-username}}/{{name}}#readme
+license:             BSD3
+author:              {{author-name}}{{^author-name}}Author name here{{/author-name}}
+maintainer:          {{author-email}}{{^author-email}}example@example.com{{/author-email}}
+copyright:           {{copyright}}{{^copyright}}{{year}}{{^year}}2019{{/year}} {{author-name}}{{^author-name}}Author name here{{/author-name}}{{/copyright}}
+category:            {{category}}{{^category}}Web{{/category}}
+extra-source-files:
+- README.md
+
+ghc-options: -O2 -flate-specialise -fspecialise-aggressively
```
Comment (isovector) [inline polysemy-template.hsfiles]: Also `-fplugin=Polysemy.Plugin`?

File: polysemy-template.hsfiles [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+  {-# LANGUAGE TemplateHaskell #-}
+  module Main where
+  import Prelude hiding (throw, catch, bracket)
+  import Polysemy
+  import Polysemy.Input
+  import Polysemy.Output
+  import Polysemy.Error
+  import Polysemy.Resource
+  
+  import Teletype hiding (main)
```
Comment (isovector) [inline polysemy-template.hsfiles]: No point in defining main if we're just going to hide its import. Remove it from `Teletype`?

File: polysemy-template.hsfiles [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+              _             -> writeTTY input >> writeTTY "no exceptions"
+  
+  main :: IO (Either CustomException ())
+  main = (runM .@ runResource .@@ runErrorInIO @CustomException) . runTeletypeIO $ program
+
+
+
+{-# START_FILE src/Teletype.hs #-}
+  {-# LANGUAGE TemplateHaskell,BlockArguments #-}
+  module Teletype where
```
Comment (isovector) [inline polysemy-template.hsfiles]: `Polysemy.Teletype`

**Comment by isovector** [comment]
This is super cool! Thanks for putting it together; I can't wait to merge it!

File: polysemy-template.hsfiles (hunk 1 above)
Comment (csasarak) [reply polysemy-template.hsfiles]: Yeah, I forgot that thanks!

File: polysemy-template.hsfiles (hunk 2 above)
Comment (csasarak) [reply polysemy-template.hsfiles]: I was mainly doing this in order to have something quickly buildable to tinker with. I left the definition in case someone wanted to swap the Teletype example in. I made the resource example the primary one just because it shows off a few more things than Teletype. 

Do you still think it should be removed? Or perhaps there's even better ways to promote "play" with the code?

Comment (csasarak) [reply polysemy-template.hsfiles]: I agree now, better to use the imported version of Teletype. It's less maintenance work than having it in both places.

**Comment by csasarak** [comment]
So I did some digging and it looks like the issue I was running into is because stack doesn't understand cabal's output, therefore the `--solver` option breaks. Because `stack` is deprecating the solver option I'm not sure this PR is worth merging - I think folks would still need to do some configuration of their `stack.yaml` and `extra-deps` to get it to work. I think it's not much of an improvement if people are told to use this but then have to go edit the files themselves. I also don't think I can really use the template system to edit the `stack.yaml`, and in general think templates should probably leave that alone.

If `polysemy` gets on stackage this will eventually work. I also don't know if the work on the solver means that you must use `extra-deps` from now on for packages that only exist on hackage, or if it means stack will be smart enough to try going to hackage as a fall-back. This is the relevant PR: https://github.com/commercialhaskell/stack/pull/4670

**Comment by isovector** [comment]
There's no reason to not put it on stackage, other than I have never looked into how to do that!

**Comment by isovector** [comment]
https://github.com/commercialhaskell/stackage/pull/4562

**Comment by isovector** [comment]
`polysemy`, `polysemy-plugin` and `polysemy-zoo` are now all in stackage!

**Comment by csasarak** [comment]
@isovector Very cool! I will work on updating the documentation for this template and see what other changes itmight need. I think for a while folks will need to use the nightly resolver (I'll check tonight's or tomorrows') but it should make it's way into LTS.

**Comment by csasarak** [comment]
This is nearly done, but I'm getting a type error I don't quite understand when I run `stack build` in the generated project directory:

```haskell
polysemy-base/src/Main.hs:26:66: error:
    • Couldn't match type ‘Lift IO’ with ‘Error CustomException’
        arising from a use of ‘runTeletypeIO’
    • In the second argument of ‘(.)’, namely ‘runTeletypeIO’
      In the expression:
        (runM .@ runResource .@@ runErrorInIO @CustomException)
          . runTeletypeIO
      In the expression:
        (runM .@ runResource .@@ runErrorInIO @CustomException)
          . runTeletypeIO
          $ program
   |
26 | main = (runM .@ runResource .@@ runErrorInIO @CustomException) . runTeletypeIO $ program

polysemy-base/src/Main.hs:26:82: error:
    • Couldn't match type ‘Resource’ with ‘Error CustomException’
        arising from a use of ‘program’
    • In the second argument of ‘($)’, namely ‘program’
      In the expression:
        (runM .@ runResource .@@ runErrorInIO @CustomException)
          . runTeletypeIO
          $ program
      In an equation for ‘main’:
          main
            = (runM .@ runResource .@@ runErrorInIO @CustomException)
                . runTeletypeIO
                $ program
   |
26 | main = (runM .@ runResource .@@ runErrorInIO @CustomException) . runTeletypeIO $ program
```

**Comment by isovector** [comment]
Oh man, there are some problems here. First of all, `throw, catch, bracket` aren't a part of `Prelude`.

But more pressingly, the code included works in version `polysemy-0.1.2.0`, `polysemy-plugin-0.1.0.0`, though not in `polysemy-0.1.2.1`, `polysemy-plugin-0.1.0.1`. I'll run a bisect tomorrow and try to figure out what's going wrong.

**Comment by jhenahan** [comment]
My bad on the hiding clause. I use a custom Prelude and I always forget what's actually exported from the real one. I'll fix it.

**Comment by boj** [comment]
@isovector For what it is worth, I am experiencing something similar to the error above in some custom code built via cabal. Using the latest version on hackage.

**Comment by isovector** [comment]
@boj @csasarak me too; looks like I broke something in the plugin without realizing it.

**Comment by isovector** [comment]
@boj @csasarak can either of you confirm that downgrading `polysemy-plugin` to `0.1.0.0` fixes it? This is the case on my machine.

**Comment by boj** [comment]
@isovector Confirmed.

**Comment by isovector** [comment]
@boj @csasarak okay, `polysemy-plugin-0.2.0.0` is out. I'm reasonably confident it will fix your issues.

**Comment by boj** [comment]
@isovector Yep, that works. Thanks!

**Comment by isovector** [comment]
What's the state of this?

**Comment by csasarak** [comment]
It's ready to go, sorry! 

On June 8, 2019 9:58:30 AM EDT, Sandy Maguire <notifications@github.com> wrote:
>What's the state of this?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/isovector/polysemy/pull/46#issuecomment-500126274

-- 
Chris

**Comment by isovector** [comment]
Very cool, thanks! Is it possible to add a CI test for this so that travis will attempt to build the stack template against HEAD? I'm worried about forgetting to update this file when I do big changes to the library.

**Comment by csasarak** [comment]
I can look into it this weekend. I have no CI experience 

On June 8, 2019 7:14:26 PM EDT, Sandy Maguire <notifications@github.com> wrote:
>Very cool, thanks! Is it possible to add a CI test for this so that
>travis will attempt to build the stack template against HEAD? I'm
>worried about forgetting to update this file when I do big changes to
>the library.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/isovector/polysemy/pull/46#issuecomment-500172306

-- 
Chris

**Comment by isovector** [comment]
A shell script that does the right commands and calls `stack build` on the
resulting project would be sufficient; I can hook it up to CI from there.

**Comment by csasarak** [comment]
@isovector I've added a very basic script that will hopefully be usable: https://github.com/isovector/polysemy/pull/46/commits/67c9f54c43c6a81d26db8b3bea1b5e48b57bf499#diff-54c98af0b66f3c4ef88b2693f668190d

**Comment by csasarak** [comment]
I forgot a `1`. I can fix it later when I get home

**Comment by isovector** [comment]
Todo for myself:

- [ ] Update the CI to run the script before merging this.

**Comment by isovector** [comment]
Closing this due to being stale. Please feel free to reopen if you still think it's something that should get pushed through!
