### ISSUE TITLE
Polysemy-plugin doesn't compile on GHC 9.4

### ISSUE THREAD

**Issue by spacekitteh** [polysemy-research/polysemy#457]
```
src/Polysemy/Plugin/Fundep/Stuff.hs:94:5: error:
    • Couldn't match expected type ‘GHC.Types.PkgQual.PkgQual’
                  with actual type ‘Maybe a0’
    • In the third argument of ‘lookupModuleWithSuggestions’, namely
        ‘Nothing’
      In the expression:
        lookupModuleWithSuggestions
          theUnitState (mkModuleName "Polysemy") Nothing
      In a stmt of a 'do' block:
        case
            lookupModuleWithSuggestions
              theUnitState (mkModuleName "Polysemy") Nothing
        of
          LookupHidden _ _ -> error_msg
          LookupNotFound _ -> error_msg
          LookupUnusable _ -> error_msg
          _ -> pure ()
   |
94 |     Nothing of
   |     ^^^^^^^
```

**Comment by teto** [comment]
I concur, I have with current master
```
       > src/Polysemy/Plugin/Fundep.hs:314:18: error:
       >     Not in scope: type constructor or class ‘TcPluginResult’
       >     |
       > 314 |     -> TcPluginM TcPluginResult
       >     |                  ^^^^^^^^^^^^^^
       For full logs, run 'nix log /nix/store/ph8mdlr1ig1112lviysxm153q0ixham1-polysemy-plugin-0.4.3.1.drv'.
```

**Comment by tek** [comment]
this should be closed, Sophie fixed it: https://github.com/polysemy-research/polysemy/pull/458

are you certain you built with this patch included, @teto?

**Comment by teto** [comment]
@tek I build with the mentioned patch but my error is different and seems LGTM: https://downloads.haskell.org/~ghc/9.4.1-rc1/docs/users_guide/9.4.1-notes.html#compiler TcPluginResult has been renamed TcPluginSolveResult in ghc 9.4

**Comment by spacekitteh** [comment]
huh maybe i didn't fix it

**Comment by teto** [comment]
I've got a crappy PR https://github.com/polysemy-research/polysemy/pull/461 that gives a shell to develop for 9.4 (but breaks everything else :) ). Seems like ghc is doing a lot of work to improve the error messages and this makes building polysemy-plugin on ghc 9.4 non-trivial.

**Comment by isovector** [comment]
This sucks. I'll try to take a look this week.

**Comment by tek** [comment]
this was fixed in 0.4.4.0!
